# Generated by Django 5.2 on 2025-10-21 14:11

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
import tools.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('base_url', models.URLField(help_text='Base URL such as https://api.example.com')),
                ('auth_profile', models.CharField(choices=[('none', 'None'), ('oauth2_cc', 'OAuth2 Client Credentials'), ('api_key_hdr', 'API Key (Header)'), ('api_key_qs', 'API Key (Query)'), ('bearer_jwt', 'Bearer JWT'), ('mtls', 'mTLS')], default='none', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('domain_allowlist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('owner_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_providers', to='accounts.team')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_providers', to='accounts.tenant')),
            ],
            options={
                'ordering': ('tenant__slug', 'name'),
            },
        ),
        migrations.CreateModel(
            name='NormalizedCapability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('json_schema_in', models.JSONField()),
                ('json_schema_out', models.JSONField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('enabled', models.BooleanField(default=False)),
                ('wire', models.JSONField(blank=True, help_text='Wire format details such as HTTP method, path, path_map, query_map headers.', null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='tools.apiprovider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='accounts.tenant')),
            ],
            options={
                'ordering': ('provider__name', 'name', 'version'),
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('actor', models.CharField(max_length=200)),
                ('latency_ms', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('upstream_error', 'Upstream Error'), ('policy_blocked', 'Policy Blocked'), ('rate_limited', 'Rate Limited'), ('validation_error', 'Validation Error'), ('timeout', 'Timeout')], max_length=20)),
                ('pii_touched', models.BooleanField(default=False)),
                ('error_kind', models.CharField(blank=True, default='', max_length=120)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='accounts.tenant')),
                ('capability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='tools.normalizedcapability')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(help_text='Pinned capability version')),
                ('scopes', models.JSONField(default=list, help_text="List of scope strings (e.g., ['read', 'write']).")),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_access_grants', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='accounts.team')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='tools.normalizedcapability')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('openapi', 'OpenAPI 3.x'), ('graphql', 'GraphQL Introspection/SDL'), ('asyncapi', 'AsyncAPI'), ('grpc', 'gRPC / Protobuf'), ('jsonschema', 'Raw JSON Schema')], max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
                ('blob', models.FileField(blank=True, null=True, upload_to=tools.models._schema_upload_path)),
                ('etag', models.CharField(blank=True, default='', max_length=200)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('content_size', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_by_type', models.CharField(choices=[('user', 'User'), ('sp', 'ServicePrincipal')], default='user', max_length=24)),
                ('created_by_identifier', models.CharField(help_text='Email for user, or service token id:name for service principal', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Null if created by service principal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_schema_sources', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_sources', to='tools.apiprovider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_sources', to='accounts.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='apiprovider',
            index=models.Index(fields=['tenant', 'name'], name='tools_apipr_tenant__d08d78_idx'),
        ),
        migrations.AddIndex(
            model_name='apiprovider',
            index=models.Index(django.db.models.functions.text.Lower('base_url'), name='api_provider_base_url_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apiprovider',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='normalizedcapability',
            index=models.Index(fields=['provider', 'version'], name='tools_norma_provide_52b44c_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedcapability',
            index=models.Index(fields=['tenant', 'enabled'], name='tools_norma_tenant__307a1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='normalizedcapability',
            unique_together={('provider', 'version', 'name')},
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['tenant', 'timestamp'], name='tools_execu_tenant__21caff_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['status'], name='tools_execu_status_8dd0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['team', 'expires_at'], name='tools_acces_team_id_aafe62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accessgrant',
            unique_together={('team', 'capability', 'version')},
        ),
        migrations.AddIndex(
            model_name='schemasource',
            index=models.Index(fields=['tenant', 'provider'], name='tools_schem_tenant__acce14_idx'),
        ),
        migrations.AddIndex(
            model_name='schemasource',
            index=models.Index(fields=['provider', 'kind'], name='tools_schem_provide_d69461_idx'),
        ),
    ]
