# Generated by Django 5.2 on 2025-10-24 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgrant',
            name='approved_by_identifier',
            field=models.CharField(help_text='Email for user, or service token id:name for service principal', null=True),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='approved_by_type',
            field=models.CharField(choices=[('User', 'User'), ('ServicePrincipal', 'ServicePrincipal')], default='User', max_length=24),
        ),
        migrations.AddField(
            model_name='normalizedcapability',
            name='created_by_identifier',
            field=models.CharField(help_text='Email for user, or service token id:name for service principal', null=True),
        ),
        migrations.AddField(
            model_name='normalizedcapability',
            name='created_by_type',
            field=models.CharField(choices=[('User', 'User'), ('ServicePrincipal', 'ServicePrincipal')], default='User', max_length=24),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Null if approved by service principal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='version',
            field=models.PositiveIntegerField(blank=True, help_text='Pinned capability version', null=True),
        ),
        migrations.AlterField(
            model_name='normalizedcapability',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='schemasource',
            name='created_by_type',
            field=models.CharField(choices=[('User', 'User'), ('ServicePrincipal', 'ServicePrincipal')], default='User', max_length=24),
        ),
    ]
