# Generated by Django 5.2 on 2025-10-27 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_accessgrant_approved_by_identifier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedcapability',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Null if created by service principal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_capabilities', to=settings.AUTH_USER_MODEL),
        ),
    ]
