# Generated by Django 5.2 on 2025-11-03 13:12

import core.storages
import tools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_normalizedcapability_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemasource',
            name='blob',
            field=models.FileField(blank=True, null=True, storage=core.storages.AzureMediaStorage(), upload_to=tools.models._schema_upload_path),
        ),
    ]
