# Generated by Django 5.2 on 2025-10-24 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_default',
        ),
        migrations.AddField(
            model_name='servicetoken',
            name='owner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_service_tokens', to='accounts.team'),
        ),
        migrations.AddField(
            model_name='servicetoken',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsored_service_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='default_team',
            field=models.ForeignKey(blank=True, help_text='Default team for resource ownership. Must be a team the user is a member of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='accounts.team'),
        ),
    ]
